/**
 * Interview-related type definitions
 */

import type { TranscriptEntry } from '@/lib/gemini/types';

/**
 * Model answer generated by AI analysis
 * Contains an ideal answer transcript
 */
export interface ModelAnswer {
  /** Ideal answer transcript (interviewer questions + ideal candidate responses) */
  transcript: TranscriptEntry[];
}
