/**
 * Interview-related type definitions
 */

import type { TranscriptEntry } from '@/lib/gemini/types';

/**
 * Model answer generated by AI analysis
 * Contains an ideal answer transcript and optional audio file
 */
export interface ModelAnswer {
  /** Ideal answer transcript (questions + AI responses) */
  transcript: TranscriptEntry[];
  /** URL to the TTS-generated audio file (e.g., "/model-answers/abc123.mp3") */
  audioUrl?: string;
}
